<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Doctor;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $doctors = 
        [
        ['first_name' => 'Alberto', 'middle_name' => null, 'last_name' => 'Chavez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Chavez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alfonso', 'middle_name' => null, 'last_name' => 'Espinoza', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alberto', 'middle_name' => null, 'last_name' => 'Martinez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Angel', 'middle_name' => null, 'last_name' => 'Martinez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alvaro', 'middle_name' => null, 'last_name' => 'Mercado', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Arturo', 'middle_name' => null, 'last_name' => 'Mercado', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernanda', 'middle_name' => null, 'last_name' => 'Espinoza', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernando', 'middle_name' => null, 'last_name' => 'Espinoza', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Javier', 'middle_name' => null, 'last_name' => 'Castillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jesus', 'middle_name' => null, 'last_name' => 'Castillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jonathan', 'middle_name' => null, 'last_name' => 'Ramirez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Ramirez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Manuel', 'middle_name' => null, 'last_name' => 'Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Miguel', 'middle_name' => null, 'last_name' => 'Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ruben', 'middle_name' => null, 'last_name' => 'Cardenas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rafael', 'middle_name' => null, 'last_name' => 'Cardenas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Raul', 'middle_name' => null, 'last_name' => 'Flores', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ramiro', 'middle_name' => null, 'last_name' => 'Flores', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ricardo', 'middle_name' => null, 'last_name' => 'Muñoz', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rafael', 'middle_name' => null, 'last_name' => 'Ortega', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ricardo', 'middle_name' => null, 'last_name' => 'Ortega', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Arturo', 'middle_name' => null, 'last_name' => 'Agraz', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Armando', 'middle_name' => null, 'last_name' => 'Ahumada', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Andres', 'middle_name' => null, 'last_name' => 'Arcas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Aaron', 'middle_name' => null, 'last_name' => 'Avila', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alexis', 'middle_name' => null, 'last_name' => 'Barba', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Arturo', 'middle_name' => null, 'last_name' => 'Carlin', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Bolaños', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alexis', 'middle_name' => null, 'last_name' => 'Campusano', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Arturo', 'middle_name' => null, 'last_name' => 'Chagollan', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Antonio', 'middle_name' => null, 'last_name' => 'Cuevas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Antonio', 'middle_name' => null, 'last_name' => 'Flores', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Fuentes', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Arnoldo', 'middle_name' => null, 'last_name' => 'Garcia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alex', 'middle_name' => null, 'last_name' => 'Garmendia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Izaguirre', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alfonso', 'middle_name' => null, 'last_name' => 'Limon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Arturo', 'middle_name' => null, 'last_name' => 'Lopez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ambrosio', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alberto', 'middle_name' => null, 'last_name' => 'Molina', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alan', 'middle_name' => null, 'last_name' => 'Montes', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Moya', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Aaron', 'middle_name' => null, 'last_name' => 'Piscil', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alvaro', 'middle_name' => null, 'last_name' => 'Ramirez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Arnulfo', 'middle_name' => null, 'last_name' => 'Ramos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Antonio', 'middle_name' => null, 'last_name' => 'Reyna', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Antonio', 'middle_name' => null, 'last_name' => 'Ramirez Reina', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alberto', 'middle_name' => null, 'last_name' => 'Robledo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Arturo', 'middle_name' => null, 'last_name' => 'Salinas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Artemio', 'middle_name' => null, 'last_name' => 'Sanchez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Adrian', 'middle_name' => null, 'last_name' => 'Sandoval', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Adrian', 'middle_name' => null, 'last_name' => 'Sedano', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alexandro', 'middle_name' => null, 'last_name' => 'Vazquez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Bernardo', 'middle_name' => null, 'last_name' => 'Luna', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Alonso Gomez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Campos', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cesar', 'middle_name' => null, 'last_name' => 'Alvarez Rengiffo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Castellanos', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Christian', 'middle_name' => null, 'last_name' => 'Avila', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Brambila', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Campos Dorador', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Cuevas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cesar', 'middle_name' => null, 'last_name' => 'Curiel', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Damian', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Christian', 'middle_name' => null, 'last_name' => 'Garcia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Gomez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Haro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Juarez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cesar', 'middle_name' => null, 'last_name' => 'Maldonado', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cruz', 'middle_name' => null, 'last_name' => 'Malpica', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Celso', 'middle_name' => null, 'last_name' => 'Montiel', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Crisanto', 'middle_name' => null, 'last_name' => 'Mora', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Luis Contreras', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cesar', 'middle_name' => null, 'last_name' => 'Perez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Romero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Christian', 'middle_name' => null, 'last_name' => 'Saldivar', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Tello', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Del Toro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cuevas', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Zazueta', 'phone' => null, 'is_active' => true],
        ['first_name' => 'David', 'middle_name' => null, 'last_name' => 'Aguayo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'David', 'middle_name' => null, 'last_name' => 'Avila', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Diego', 'middle_name' => null, 'last_name' => 'Ayala', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Diego', 'middle_name' => null, 'last_name' => 'Barba', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Becerra', 'phone' => null, 'is_active' => true],
        ['first_name' => 'David', 'middle_name' => null, 'last_name' => 'Chung', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Copado', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Diego', 'middle_name' => null, 'last_name' => 'Cordero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Diego', 'middle_name' => null, 'last_name' => 'Estrada', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Figueroa', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Diego', 'middle_name' => null, 'last_name' => 'Gomez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Diego', 'middle_name' => null, 'last_name' => 'Hernandez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Macias', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Montaño', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Paz', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Ramirez Islas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Ronquillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Sandoval', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Diego', 'middle_name' => null, 'last_name' => 'Zulueta', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Esteban', 'middle_name' => null, 'last_name' => 'Arce', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Enrique', 'middle_name' => null, 'last_name' => 'Avila', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Eduardo', 'middle_name' => null, 'last_name' => 'Azpeitia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Emilio', 'middle_name' => null, 'last_name' => 'Bitar', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Esteban', 'middle_name' => null, 'last_name' => 'Castro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Edgar', 'middle_name' => null, 'last_name' => 'Garcia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Emmanuel', 'middle_name' => null, 'last_name' => 'Garmendia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Enrique', 'middle_name' => null, 'last_name' => 'Hernandez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Eduardo', 'middle_name' => null, 'last_name' => 'Ibarra', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Emanuel', 'middle_name' => null, 'last_name' => 'Moreno', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alan', 'middle_name' => null, 'last_name' => 'De Endoscopic', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Enrique', 'middle_name' => null, 'last_name' => 'Nieto', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Enrique', 'middle_name' => null, 'last_name' => 'Ocegueda', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Edgar', 'middle_name' => null, 'last_name' => 'Partida', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Enrique', 'middle_name' => null, 'last_name' => 'Reynaga', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Eduardo', 'middle_name' => null, 'last_name' => 'Rodriguez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Eduardo', 'middle_name' => null, 'last_name' => 'Romano', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Emilio', 'middle_name' => null, 'last_name' => 'Ruiz', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Enrique', 'middle_name' => null, 'last_name' => 'Salcido', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Eduardo', 'middle_name' => null, 'last_name' => 'Santibañez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Erik', 'middle_name' => null, 'last_name' => 'Vargas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Felipe', 'middle_name' => null, 'last_name' => 'Amezcua', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Francisco', 'middle_name' => null, 'last_name' => 'Arroyo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernando', 'middle_name' => null, 'last_name' => 'Cardenas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Francisco', 'middle_name' => null, 'last_name' => 'Carrillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Francisco', 'middle_name' => null, 'last_name' => 'Chavez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Francisco', 'middle_name' => null, 'last_name' => 'Cruz', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Felipe', 'middle_name' => null, 'last_name' => 'De Jesus', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Francisco', 'middle_name' => null, 'last_name' => 'Esponda', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Francisco', 'middle_name' => null, 'last_name' => 'Gomez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernando', 'middle_name' => null, 'last_name' => 'De La Huerta', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Figueroa', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernando', 'middle_name' => null, 'last_name' => 'Menchaca', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Felipe', 'middle_name' => null, 'last_name' => 'Orellana', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernando', 'middle_name' => null, 'last_name' => 'Ortega', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Francisco', 'middle_name' => null, 'last_name' => 'Rodriguez Bustos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Francisco', 'middle_name' => null, 'last_name' => 'Sanchez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Francisco', 'middle_name' => null, 'last_name' => 'Sandoval', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Federico', 'middle_name' => null, 'last_name' => 'Uribe', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gustavo', 'middle_name' => null, 'last_name' => 'Beas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Guillermo', 'middle_name' => null, 'last_name' => 'Cano', 'phone' => null, 'is_active' => true],
        ['first_name' => 'German', 'middle_name' => null, 'last_name' => 'Eduardo Murcles Vencos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gerardo', 'middle_name' => null, 'last_name' => 'Franco Esqueda', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gabriel', 'middle_name' => null, 'last_name' => 'Garabito', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gibran', 'middle_name' => null, 'last_name' => 'Jacobo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gerardo', 'middle_name' => null, 'last_name' => 'Jasso', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gabriel', 'middle_name' => null, 'last_name' => 'De Leon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gabriel', 'middle_name' => null, 'last_name' => 'Martinez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Guillermo', 'middle_name' => null, 'last_name' => 'Medina', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Guillermo', 'middle_name' => null, 'last_name' => 'Montalvo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Guillermo', 'middle_name' => null, 'last_name' => 'Moreno', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Guillermo', 'middle_name' => null, 'last_name' => 'Navarro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gustavo', 'middle_name' => null, 'last_name' => 'Ramirez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gustavo', 'middle_name' => null, 'last_name' => 'Tafoya', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Garcia', 'middle_name' => null, 'last_name' => 'Valadez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gerardo', 'middle_name' => null, 'last_name' => 'Zarate', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Humberto', 'middle_name' => null, 'last_name' => 'Calvillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hugo', 'middle_name' => null, 'last_name' => 'Coss', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hugo', 'middle_name' => null, 'last_name' => 'De Anda', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hector', 'middle_name' => null, 'last_name' => 'Gomez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hector', 'middle_name' => null, 'last_name' => 'Haro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hans', 'middle_name' => null, 'last_name' => 'Hernandez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hiramuro', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hector', 'middle_name' => null, 'last_name' => 'Macias', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hector', 'middle_name' => null, 'last_name' => 'Paredes', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hugo', 'middle_name' => null, 'last_name' => 'Torrano', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Israel', 'middle_name' => null, 'last_name' => 'Barragan', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ignacio', 'middle_name' => null, 'last_name' => 'Cardona', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Israel', 'middle_name' => null, 'last_name' => 'Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Isaac', 'middle_name' => null, 'last_name' => 'Luna', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ivan', 'middle_name' => null, 'last_name' => 'Medina', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ismael', 'middle_name' => null, 'last_name' => 'Pacheco', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Isaac', 'middle_name' => null, 'last_name' => 'Lopez Peña', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Israel', 'middle_name' => null, 'last_name' => 'Romo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ivan', 'middle_name' => null, 'last_name' => 'Zaragoza', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Aceves', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Antonio Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Aguayo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Antonio Guerrero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Arce', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jaime', 'middle_name' => null, 'last_name' => 'Arellano', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Josue', 'middle_name' => null, 'last_name' => 'Astorga', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Barba', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Barbosa', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Josimar', 'middle_name' => null, 'last_name' => 'Beltran', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Cardenas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Castañeda', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Chavira', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Clifton', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Carlos Navarro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Javier', 'middle_name' => null, 'last_name' => 'Cobian', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Carlos Sierra', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jaime', 'middle_name' => null, 'last_name' => 'Del Toro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Enrique Cabrales', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Javier', 'middle_name' => null, 'last_name' => 'Enriquez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jesus', 'middle_name' => null, 'last_name' => 'Eduardo Vazquez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jaime', 'middle_name' => null, 'last_name' => 'Flores', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Guemez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jesus', 'middle_name' => null, 'last_name' => 'Guzman', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Joel', 'middle_name' => null, 'last_name' => 'Hernandez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Luis Carrillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jesus', 'middle_name' => null, 'last_name' => 'Ledezma', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Luis Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Luis Guerrero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Luis Hernandez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Josmar', 'middle_name' => null, 'last_name' => 'Lopez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Luis Ramos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Luis Romero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Mandujo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Maria Castellon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jaime', 'middle_name' => null, 'last_name' => 'Michel', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Manuel Lizarraga', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Manuel Ochoa', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Julio', 'middle_name' => null, 'last_name' => 'Morales', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Manuel Del Toro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Javier', 'middle_name' => null, 'last_name' => 'Navarro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Javier', 'middle_name' => null, 'last_name' => 'Orozco', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Pablo Alvarez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Julio', 'middle_name' => null, 'last_name' => 'Perez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Pablo Patiño', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Julio', 'middle_name' => null, 'last_name' => 'Restelli', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Rivas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Ramon Renteria', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Salazar', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Serratos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Valadez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Vigon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Kim', 'middle_name' => null, 'last_name' => 'Lee', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Antonio Badillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luciano', 'middle_name' => null, 'last_name' => 'Aguilera', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Carlos Blanco', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Chavez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Enrique Ramirez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Fernando Herrera', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Fernando Navarro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Navarro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Garcia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Ibarra', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Padilla', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Perez Gomez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Ramirez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'De Santiago', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Limon', 'middle_name' => null, 'last_name' => 'Tello', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Maya', 'middle_name' => null, 'last_name' => 'Alvarez Del Castillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Madrigal', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Martin', 'middle_name' => null, 'last_name' => 'Aguirre', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Marco', 'middle_name' => null, 'last_name' => 'Altamirano', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Miguel', 'middle_name' => null, 'last_name' => 'Brizuela', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Maurilio', 'middle_name' => null, 'last_name' => 'Cardenas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Manuel', 'middle_name' => null, 'last_name' => 'Celis', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Maximo', 'middle_name' => null, 'last_name' => 'Gomez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Mauricio', 'middle_name' => null, 'last_name' => 'Guerrero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Miguel', 'middle_name' => null, 'last_name' => 'Gutierrez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Miguel', 'middle_name' => null, 'last_name' => 'Huerta', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Marco', 'middle_name' => null, 'last_name' => 'Larios', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Mario', 'middle_name' => null, 'last_name' => 'Lopez Rico', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Moises', 'middle_name' => null, 'last_name' => 'Madrigal', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Manuel', 'middle_name' => null, 'last_name' => 'Medina', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Miguel', 'middle_name' => null, 'last_name' => 'Morales', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Miguel', 'middle_name' => null, 'last_name' => 'Olmedo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Marco', 'middle_name' => null, 'last_name' => 'Polo Malacon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Mario', 'middle_name' => null, 'last_name' => 'Sanchez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Mario', 'middle_name' => null, 'last_name' => 'Santillan', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Miguel', 'middle_name' => null, 'last_name' => 'Schiavon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Mario', 'middle_name' => null, 'last_name' => 'Suarez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Manuel', 'middle_name' => null, 'last_name' => 'Del Toro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Munguia', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Miguel', 'middle_name' => null, 'last_name' => 'Valenzuela', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Nicolas', 'middle_name' => null, 'last_name' => 'Ceniceros', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Nestor', 'middle_name' => null, 'last_name' => 'Ivan Lopez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Napoleon', 'middle_name' => null, 'last_name' => 'Mejia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Navid', 'middle_name' => null, 'last_name' => 'Rodriguez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Noe', 'middle_name' => null, 'last_name' => 'Saavedra', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Nicolas', 'middle_name' => null, 'last_name' => 'Valladares', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Omar', 'middle_name' => null, 'last_name' => 'Bautista', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Omar', 'middle_name' => null, 'last_name' => 'Fregoso', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Oscar', 'middle_name' => null, 'last_name' => 'Galaviz', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Omar', 'middle_name' => null, 'last_name' => 'Maya', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Oscar', 'middle_name' => null, 'last_name' => 'Mendoza', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Octavio', 'middle_name' => null, 'last_name' => 'Ochoa', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Oscar', 'middle_name' => null, 'last_name' => 'Orozco', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Oscar', 'middle_name' => null, 'last_name' => 'Ortiz', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Oscar', 'middle_name' => null, 'last_name' => 'Ramirez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Oscar', 'middle_name' => null, 'last_name' => 'Rodriguez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Oscar', 'middle_name' => null, 'last_name' => 'Fernando Romo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Oswaldo', 'middle_name' => null, 'last_name' => 'Sanchez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Pablo', 'middle_name' => null, 'last_name' => 'Fernandez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Paul', 'middle_name' => null, 'last_name' => 'Leal', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Pedro', 'middle_name' => null, 'last_name' => 'Lomeli', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Pablo', 'middle_name' => null, 'last_name' => 'Zarate', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rafael', 'middle_name' => null, 'last_name' => 'Alferez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Raul', 'middle_name' => null, 'last_name' => 'Alonso', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ramiro', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ramon', 'middle_name' => null, 'last_name' => 'Arreola', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rafael', 'middle_name' => null, 'last_name' => 'Castro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ruben', 'middle_name' => null, 'last_name' => 'Cruz', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ramon', 'middle_name' => null, 'last_name' => 'Davalos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rene', 'middle_name' => null, 'last_name' => 'Dueñez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Raul', 'middle_name' => null, 'last_name' => 'Rodriguez Emerico', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Renato', 'middle_name' => null, 'last_name' => 'Escutia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rafael', 'middle_name' => null, 'last_name' => 'Estrada', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ramon', 'middle_name' => null, 'last_name' => 'Flaco', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ramon', 'middle_name' => null, 'last_name' => 'Gil', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Roberto', 'middle_name' => null, 'last_name' => 'Garcia Valadez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rafael', 'middle_name' => null, 'last_name' => 'Jimenez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ricardo', 'middle_name' => null, 'last_name' => 'Lara', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Roberto', 'middle_name' => null, 'last_name' => 'Lopez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ricardo', 'middle_name' => null, 'last_name' => 'Madrigal', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Raul', 'middle_name' => null, 'last_name' => 'Mendoza', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Roberto', 'middle_name' => null, 'last_name' => 'Michel', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rene', 'middle_name' => null, 'last_name' => 'Mora', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Raul', 'middle_name' => null, 'last_name' => 'Moran', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ricardo', 'middle_name' => null, 'last_name' => 'Orellana', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Reyes', 'middle_name' => null, 'last_name' => 'Pedroza', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ruben', 'middle_name' => null, 'last_name' => 'Perez Manzo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ramon', 'middle_name' => null, 'last_name' => 'Del Rio', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ricardo', 'middle_name' => null, 'last_name' => 'Rivas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rene', 'middle_name' => null, 'last_name' => 'De La Rosa', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ramiro', 'middle_name' => null, 'last_name' => 'Sanchez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rafael', 'middle_name' => null, 'last_name' => 'Vazquez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Sanchez', 'middle_name' => null, 'last_name' => 'Aldana', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Salvador', 'middle_name' => null, 'last_name' => 'Berrueta', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Sanchez', 'middle_name' => null, 'last_name' => 'Bosques', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Santiago', 'middle_name' => null, 'last_name' => 'Froylan', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Santiago', 'middle_name' => null, 'last_name' => 'Garnica', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Sigifrido', 'middle_name' => null, 'last_name' => 'Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Sergio', 'middle_name' => null, 'last_name' => 'Guizar', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Salvador', 'middle_name' => null, 'last_name' => 'Magallon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Sergio', 'middle_name' => null, 'last_name' => 'Paez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Sergio', 'middle_name' => null, 'last_name' => 'Quintero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Tonatiuh', 'middle_name' => null, 'last_name' => 'Mondragon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Tellez', 'middle_name' => null, 'last_name' => 'Tampico', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Victor', 'middle_name' => null, 'last_name' => 'Herrera', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Victor', 'middle_name' => null, 'last_name' => 'Lopez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Victor', 'middle_name' => null, 'last_name' => 'Valdez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Wilfrido', 'middle_name' => null, 'last_name' => 'Castillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Yair', 'middle_name' => null, 'last_name' => 'Galindo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Yair', 'middle_name' => null, 'last_name' => 'Molina', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Manuel', 'middle_name' => null, 'last_name' => 'Romero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ignacion', 'middle_name' => null, 'last_name' => 'Madrigal', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Abel', 'middle_name' => null, 'last_name' => 'Abreu', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Mora', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Antonio', 'middle_name' => null, 'last_name' => 'Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernando', 'middle_name' => null, 'last_name' => 'Navarro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hector', 'middle_name' => null, 'last_name' => 'Mejia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Quality', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Edson', 'middle_name' => null, 'last_name' => 'Morales', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cap', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Vistas', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Miroslava', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Solis', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Priscila', 'middle_name' => null, 'last_name' => 'Sanchez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Oscar', 'middle_name' => null, 'last_name' => 'Chavarreti', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Sergio', 'middle_name' => null, 'last_name' => 'Gudiño', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Nicolas', 'middle_name' => null, 'last_name' => 'Valladares', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Arce', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ignacio', 'middle_name' => null, 'last_name' => 'Ibarra', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Elsa', 'middle_name' => null, 'last_name' => 'Sanchez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Francisco', 'middle_name' => null, 'last_name' => 'Avila', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ramiro', 'middle_name' => null, 'last_name' => 'Padilla', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alondra', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Armando', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Arturo', 'middle_name' => null, 'last_name' => 'Salinas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jesus', 'middle_name' => null, 'last_name' => 'Brizuela', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Antonio', 'middle_name' => null, 'last_name' => 'Guerrero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ivan', 'middle_name' => null, 'last_name' => 'Perez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Paulo', 'middle_name' => null, 'last_name' => 'Padilla', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ortotecnia', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ariel', 'middle_name' => null, 'last_name' => 'De La Rosa', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Carlin', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Guillen', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Higinio', 'middle_name' => null, 'last_name' => 'Regla', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hector', 'middle_name' => null, 'last_name' => 'Macias', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Rueda', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'De Jesus Vazquez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Pablo', 'middle_name' => null, 'last_name' => 'Segura', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Diego', 'middle_name' => null, 'last_name' => 'Tablero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alan', 'middle_name' => null, 'last_name' => 'Osbaldo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Gonzalez Ross', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Luis', 'middle_name' => null, 'last_name' => 'Alberto Bobadilla', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Manuel', 'middle_name' => null, 'last_name' => 'Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Inoas', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rafael', 'middle_name' => null, 'last_name' => 'Bustos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Carlos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ignacio', 'middle_name' => null, 'last_name' => 'Casillas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Nestor', 'middle_name' => null, 'last_name' => 'Y Beto', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cesar', 'middle_name' => null, 'last_name' => 'Rizo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Omar', 'middle_name' => null, 'last_name' => 'Fregoso', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Garmendia', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Cacho', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Eduardo', 'middle_name' => null, 'last_name' => 'Gomez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Velasco', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernanda', 'middle_name' => null, 'last_name' => 'Ramirez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gabriela', 'middle_name' => null, 'last_name' => 'Ayon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Pensiones', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Monica', 'middle_name' => null, 'last_name' => 'Cabrero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Reginaldo', 'middle_name' => null, 'last_name' => 'Cortes', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Leo', 'middle_name' => null, 'last_name' => 'Alejandro Ruela', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jesus', 'middle_name' => null, 'last_name' => 'Castillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cristian', 'middle_name' => null, 'last_name' => 'Murillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Raul', 'middle_name' => null, 'last_name' => 'Romo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Munguia', 'middle_name' => null, 'last_name' => 'Papachoris', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Garcia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Neurospond', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Ivan Arce', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ruben', 'middle_name' => null, 'last_name' => 'Munguia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Zamudio', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Herrera', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Lopez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Traumalogic', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Andres', 'middle_name' => null, 'last_name' => 'Campos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Teresa', 'middle_name' => null, 'last_name' => 'Alvarez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rodolfo', 'middle_name' => null, 'last_name' => 'Casanova', 'phone' => null, 'is_active' => true],
        ['first_name' => 'German', 'middle_name' => null, 'last_name' => 'Kevin', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Javier', 'middle_name' => null, 'last_name' => 'Rodriguez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Victor', 'middle_name' => null, 'last_name' => 'Demetrio Castillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Don', 'middle_name' => null, 'last_name' => 'Migue', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Raquel', 'middle_name' => null, 'last_name' => 'Montes', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cesar', 'middle_name' => null, 'last_name' => 'Verela', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernando', 'middle_name' => null, 'last_name' => 'Fernandez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ana', 'middle_name' => null, 'last_name' => 'Karenina', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alberto', 'middle_name' => null, 'last_name' => 'Medina', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Roberto', 'middle_name' => null, 'last_name' => 'Garcia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'David', 'middle_name' => null, 'last_name' => 'Rosas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Angel', 'middle_name' => null, 'last_name' => 'Tovar', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Paciente', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernando', 'middle_name' => null, 'last_name' => 'Velazquez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jfmedical', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Maldonado', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Salvador', 'middle_name' => null, 'last_name' => 'Cendejas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Solicita', 'middle_name' => null, 'last_name' => 'Mario', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gerardo', 'middle_name' => null, 'last_name' => 'Lopez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Javier', 'middle_name' => null, 'last_name' => 'Ramos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Sandra', 'middle_name' => null, 'last_name' => 'Archundia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Hector', 'middle_name' => null, 'last_name' => 'Contreras', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Elio', 'middle_name' => null, 'last_name' => 'Miranda', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Javier', 'middle_name' => null, 'last_name' => 'Neri', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Guillermo', 'middle_name' => null, 'last_name' => 'Arriaga', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Josue', 'middle_name' => null, 'last_name' => 'Silva', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Herlet', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Edgar', 'middle_name' => null, 'last_name' => 'Plantillas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Mauricio', 'middle_name' => null, 'last_name' => 'Badial', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ana', 'middle_name' => null, 'last_name' => 'Leon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Erik', 'middle_name' => null, 'last_name' => 'Echavarri', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Abel', 'middle_name' => null, 'last_name' => 'De Alba', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Sior', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Curiel', 'phone' => null, 'is_active' => true],
        ['first_name' => 'David', 'middle_name' => null, 'last_name' => 'Chung Arceo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Pablo', 'middle_name' => null, 'last_name' => 'Sandoval', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alfonso', 'middle_name' => null, 'last_name' => 'Francia', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Braulio', 'middle_name' => null, 'last_name' => 'Ferreira', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Maya', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cedano', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Eduardo', 'middle_name' => null, 'last_name' => 'Navarro', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Guerrero', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Felipe', 'middle_name' => null, 'last_name' => 'Herrera', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Samuel', 'middle_name' => null, 'last_name' => 'Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rush', 'middle_name' => null, 'last_name' => 'Medical', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Oswaldo', 'middle_name' => null, 'last_name' => 'Rizo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Guillermo', 'middle_name' => null, 'last_name' => 'Ramirez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rodrigo', 'middle_name' => null, 'last_name' => 'Celis', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Salvador', 'middle_name' => null, 'last_name' => 'Arreola', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Kevin', 'middle_name' => null, 'last_name' => 'Yañez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alfredo', 'middle_name' => null, 'last_name' => 'Moreno', 'phone' => null, 'is_active' => true],
        ['first_name' => 'David', 'middle_name' => null, 'last_name' => 'Islas', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Leonardo', 'middle_name' => null, 'last_name' => 'Rodriguez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rodrigo', 'middle_name' => null, 'last_name' => 'Salcedo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Juan', 'middle_name' => null, 'last_name' => 'Ramon Torres', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Immedi', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Ponce', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Humberto', 'middle_name' => null, 'last_name' => 'Morones', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Humberto', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Martin', 'middle_name' => null, 'last_name' => 'Delgado', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Alejandro Briceño', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Alejandro', 'middle_name' => null, 'last_name' => 'Jardon', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Sergio', 'middle_name' => null, 'last_name' => 'Rubalcaba', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Gerardo', 'middle_name' => null, 'last_name' => 'Michel', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Erasmo', 'middle_name' => null, 'last_name' => 'Esparza', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Franco', 'middle_name' => null, 'last_name' => 'Becerra', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Raul', 'middle_name' => null, 'last_name' => 'Rodriguez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Guillermo', 'middle_name' => null, 'last_name' => 'Rodriguez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Manuel', 'middle_name' => null, 'last_name' => 'Lopez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Cesar', 'middle_name' => null, 'last_name' => 'Alvarez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jose', 'middle_name' => null, 'last_name' => 'Franco', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Priscila', 'middle_name' => null, 'last_name' => 'Gimenez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Christian', 'middle_name' => null, 'last_name' => 'Amezcua', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Rimac', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Quirotecnia', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Agustin', 'middle_name' => null, 'last_name' => 'Molina', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Roberto', 'middle_name' => null, 'last_name' => 'Martinez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Becerra', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Salvador', 'middle_name' => null, 'last_name' => 'Campos', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Marcela', 'middle_name' => null, 'last_name' => 'Baliño', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Daniel', 'middle_name' => null, 'last_name' => 'Ponce', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jonathan', 'middle_name' => null, 'last_name' => '', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Carlos', 'middle_name' => null, 'last_name' => 'Gonzalez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Omar', 'middle_name' => null, 'last_name' => 'Sepulveda', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernando', 'middle_name' => null, 'last_name' => 'Espinosa', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Pastor', 'middle_name' => null, 'last_name' => 'Trujillo', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Fernandez', 'middle_name' => null, 'last_name' => 'Hernandez', 'phone' => null, 'is_active' => true],
        ['first_name' => 'Jorge', 'middle_name' => null, 'last_name' => 'Ibarra', 'phone' => null, 'is_active' => true],

        ];

        foreach ($doctors as $doc)
        {
            Doctor::create($doc);
            $this->command->info("✅ Doctor Agregado :  {$doc['first_name']} - {$doc['last_name']}");
        }
    }
}
